### PR TITLE
Added a Departments object

### PR DESCRIPTION
**Pull request by Dr-Jerm**

### CODE REVIEW

**Comment by spilliams** [comment]
@Dr-Jerm How are you finding out about these? They aren't documented on float's api repo.

**Comment by Dr-Jerm** [comment]
I'm just doing HTTP calls directly to their endpoint (using Postman). Just
set the headers as specified in their README and do 'gets'. I'm mostly
guessing with GETs when it comes to finding the endpoints, but I've found a
couple. Their API is not all that well documented :/

**Comment by spilliams** [comment]
Hah, fair enough. Thanks for the help!

**Comment by Dr-Jerm** [comment]
Also I threw this together to handle their 200 request per minute
bottleneck:

https://www.npmjs.com/package/request-throttle

Super simple, but maybe you can find some use for it.

**Comment by spilliams** [comment]
Yeah, the app I wrote float-scheduler for uses [limiter](https://www.npmjs.com/package/limiter). Not sure yet if I want throttling to be inside this package or the responsibility of the end-developer.

**Pull request merged**
